### Part8 - Deep Learning - Artificial Neural Networks(ANN)

### Lecture note

- lecture note image in lecture_note_image.ipynb

#### The Neuron

- 인간의 두뇌처럼 구조를 만들어 나가는 과정이 우리에게는 필요하다.
- 생물학 내용이 많군...
- input layer : see, hear, touch ....like human mind things..
- input value : independent variable - > standardize, 정규화 해서 이용할 수 있게 사용할 거임
- output은 one row
- weight : nn에서 중요한 항목, 가중치를 줘서 모델을 발전 시킬 거임

#### The Activation Function

- Threshold function
- sigmoid function
- Rectifier : most popular
- Hyperbolic Tangent(tanh) : It's similar to sigmoid, but it goes below zero to 1

#### How do NNs work?

- input layer의 여러 input들이 hidden layer에 들어가면서 변화가 생김


#### How do Neural Networks learn?

- hard coding?, creating?
- perceptron
  - actual value
  - feed back from result are comparing output value and actual value
  - goal : minimize cost function
  - repeat this work..
  - all the rows shares weight and iteration.
  

#### Gradient Descent

- curse of dimensionality
  - reference(http://norman3.github.io/prml/docs/chapter01/4.html)
- 미분 기울기!!
- required the cost function convex(볼록한), 볼록하 경우에만 찾을 수 있는...
  
#### Stochastic Gradient Descent

- 하나의 결과를 가지고 weight를 계속 조정
- batch gradient Descent vs stochastic gradient descent
  - 한 번에 vs 하나씩 순차적으로
  - It's random and with the best gradient and method as long as you have the same starting weights.


#### backpropagation

- http://jaejunyoo.blogspot.com/2017/01/backpropagation.html
- 

### Code

In [2]:
# !conda install -c conda-forge keras -y

In [9]:
# Importing the libraries

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

In [11]:
# Importing the dataset

dataset = pd.read_csv('Churn_Modelling.csv')
X = dataset.iloc[:, 3:13].values
y = dataset.iloc[:, 13].values

In [13]:
X

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

### encoder

- 국가별 정리
  - avoid dummy trap using onehotencoder
- 성별 정리

In [16]:
# Encoding categorical data

from sklearn.preprocessing import LabelEncoder, OneHotEncoder

labelencoder_X_1 = LabelEncoder()
X[:, 1] = labelencoder_X_1.fit_transform(X[:, 1])

labelencoder_X_2 = LabelEncoder()
X[:, 2] = labelencoder_X_2.fit_transform(X[:, 2])


In [17]:
X

array([[619, 0, 0, ..., 1, 1, 101348.88],
       [608, 2, 0, ..., 0, 1, 112542.58],
       [502, 0, 0, ..., 1, 0, 113931.57],
       ...,
       [709, 0, 0, ..., 0, 1, 42085.58],
       [772, 1, 1, ..., 1, 0, 92888.52],
       [792, 0, 0, ..., 1, 0, 38190.78]], dtype=object)

In [18]:
onehotencoder = OneHotEncoder(categorical_features = [1])
X = onehotencoder.fit_transform(X).toarray()

/Users/wontaek/anaconda3/lib/python3.6/site-packages/sklearn/preprocessing/_encoders.py:371: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
/Users/wontaek/anaconda3/lib/python3.6/site-packages/sklearn/preprocessing/_encoders.py:392: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


In [19]:
X

array([[1.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        1.0000000e+00, 1.0134888e+05],
       [0.0000000e+00, 0.0000000e+00, 1.0000000e+00, ..., 0.0000000e+00,
        1.0000000e+00, 1.1254258e+05],
       [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        0.0000000e+00, 1.1393157e+05],
       ...,
       [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 0.0000000e+00,
        1.0000000e+00, 4.2085580e+04],
       [0.0000000e+00, 1.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        0.0000000e+00, 9.2888520e+04],
       [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        0.0000000e+00, 3.8190780e+04]])

In [20]:
X = X[:, 1:]

In [22]:
# Splitting the dataset into the Training set and Test set

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, 
    y, 
    test_size = 0.2, 
    random_state = 0
)

In [23]:
# Feature Scaling

from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

#### part 2 - ANN

In [25]:
# importing the Keras libraries and packages
# Sequential : required to initializa neural network
# Dense : requeired to build the layers

import keras
from keras.models import Sequential
from keras.layers import Dense

In [27]:
# initialising the ANN

classifier = Sequential()

In [28]:
# Adding the input layer and the first hidden layer
# output_dim : the number of nodes of the layer we are adding in this function
# how many node in this layer???
# parameter tunning....we need.
# average node : (input layer + output layer) / 2
# init : randomly initialized the weights as small numbers close to zero, 균일하게 랜덤 분포 
# activation : relu (https://pythonkim.tistory.com/40)
# input_dim : input layer~

classifier.add(Dense(
    output_dim = 6,
    init = 'uniform',
    activation = "relu",
    input_dim = 11)
              )

/Users/wontaek/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:14: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", input_dim=11, units=6, kernel_initializer="uniform")`
  


In [30]:
# Adding the second hidden layer

classifier.add(Dense(
    output_dim = 6,
    init = 'uniform',
    activation = "relu")
              )

/Users/wontaek/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:6: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=6, kernel_initializer="uniform")`
  


### remember

- sigmoid function
  - the heart of probabilistic apprach
  - managed to get some probabilities in the logistic regression model


- more than two categories...?
  - input three
  - activation function : Soft Max function
  
지금 작업하는 건 두 개 카테고리가 결과니까 sigmoid로 충분

In [31]:
# Adding the output layer

classifier.add(Dense(
    output_dim = 1,
    init = 'uniform',
    activation = "sigmoid")
              )

/Users/wontaek/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:6: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="sigmoid", units=1, kernel_initializer="uniform")`
  


In [32]:
# compiling the ANN
# optimizer : the algorithm you want to use to find the optimal set of weights
# loss : lost function
# metric : 

classifier.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

In [34]:
# Fitting the ANN to the Training set
# batch size : the number of observations after which you want to update the weights
# 실험적으로 알아내야 함...

classifier.fit(
    X_train, 
    y_train,
    batch_size=10,
    nb_epoch=100
)

/Users/wontaek/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:9: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  if __name__ == '__main__':


Epoch 1/100
8000/8000 [==============================] - 2s 228us/step - loss: 0.4841 - acc: 0.7957
Epoch 2/100
8000/8000 [==============================] - 2s 220us/step - loss: 0.4277 - acc: 0.7960
Epoch 3/100
8000/8000 [==============================] - 2s 212us/step - loss: 0.4220 - acc: 0.8014
Epoch 4/100
8000/8000 [==============================] - 2s 213us/step - loss: 0.4179 - acc: 0.8231
Epoch 5/100
8000/8000 [==============================] - 2s 221us/step - loss: 0.4156 - acc: 0.8267
Epoch 6/100
8000/8000 [==============================] - 2s 250us/step - loss: 0.4136 - acc: 0.8299
Epoch 7/100
8000/8000 [==============================] - 2s 215us/step - loss: 0.4127 - acc: 0.8310
Epoch 8/100
8000/8000 [==============================] - 2s 203us/step - loss: 0.4111 - acc: 0.8332
Epoch 9/100
8000/8000 [==============================] - 2s 201us/step - loss: 0.4106 - acc: 0.8344
Epoch 10/100
8000/8000 [==============================] - 2s 201us/step - loss: 0.4096 - acc: 0.8336

In [38]:
# Predicting the Test set results
# 확률 결과로 나왔기 때문에 threshold 값을 정해주고 결과를 다시 정리 해야 함

y_pred = classifier.predict(X_test)
y_pred = (y_pred > 0.5)

In [39]:
y_pred

array([[False],
       [False],
       [False],
       ...,
       [False],
       [False],
       [False]])

In [40]:
# Making the Confusion Matrix

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)

In [41]:
cm

array([[1544,   51],
       [ 265,  140]])

In [42]:
(1544 + 175) / 2000

0.8595