### lab04-1

In [2]:
import tensorflow as tf

In [3]:
tf.set_random_seed(0)  # for reproducibility

In [14]:
x1_data = [ 73.,  93.,  89.,  96.,  73.]
x2_data = [ 80.,  88.,  91.,  98.,  66.]
x3_data = [ 75.,  93.,  90., 100.,  70.]
Y  = [152., 185., 180., 196., 142.]

In [15]:
# placeholders for a tensor that will be always fed.

x1 = tf.placeholder(tf.float32)
x2 = tf.placeholder(tf.float32)
x3 = tf.placeholder(tf.float32)

Y = tf.placeholder(tf.float32)

In [16]:
w1 = tf.Variable(tf.random_normal([1]), name='weight1')
w2 = tf.Variable(tf.random_normal([1]), name='weight2')
w3 = tf.Variable(tf.random_normal([1]), name='weight3')
b = tf.Variable(tf.random_normal([1]), name='bias')


hypothesis = x1 * w1 + x2 * w2 + x3 * w3 + b

In [17]:
# cost/loss function

cost = tf.reduce_mean(tf.square(hypothesis - Y))

In [18]:
# Minimize

optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

In [19]:
# Launch the graph in a session

sess = tf.Session()

In [20]:
sess.run(tf.global_variables_initializer())

In [21]:
for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train], 
                                  feed_dict = {x1 : x1_data, x2: x2_data, x3: x3_data, Y:y_data}
                                  )
    if step %10 == 0:
        print(step, 'cost:', cost_val, "\nPrediction:\n", hy_val)

0 cost: 42612.258 
Prediction:
 [-33.60812  -34.32662  -37.0049   -39.10783  -25.749607]
10 cost: 1.9694242 
Prediction:
 [149.001   185.14941 179.252   196.38972 141.65439]
20 cost: 1.575162 
Prediction:
 [149.55696 185.81114 179.90741 197.10265 142.15817]
30 cost: 1.5710003 
Prediction:
 [149.5621  185.81085 179.91052 197.10522 142.15701]
40 cost: 1.566883 
Prediction:
 [149.56554 185.80855 179.91164 197.10564 142.15431]
50 cost: 1.5627527 
Prediction:
 [149.56897 185.80621 179.91272 197.10602 142.1516 ]
60 cost: 1.5586569 
Prediction:
 [149.5724  185.80391 179.91383 197.10643 142.14891]
70 cost: 1.5545936 
Prediction:
 [149.5758  185.8016  179.91493 197.10683 142.14621]
80 cost: 1.5505475 
Prediction:
 [149.57921 185.79932 179.91603 197.10722 142.14354]
90 cost: 1.5465262 
Prediction:
 [149.5826  185.79703 179.9171  197.10762 142.14085]
100 cost: 1.5425093 
Prediction:
 [149.58598 185.79474 179.91821 197.108   142.13821]
110 cost: 1.5385134 
Prediction:
 [149.58937 185.79247 179.919

1080 cost: 1.2318261 
Prediction:
 [149.8791  185.59769 180.01292 197.13832 141.9119 ]
1090 cost: 1.2293257 
Prediction:
 [149.88176 185.59592 180.01378 197.13853 141.9099 ]
1100 cost: 1.2268726 
Prediction:
 [149.88437 185.59413 180.01462 197.13876 141.90791]
1110 cost: 1.2244364 
Prediction:
 [149.88698 185.59239 180.01547 197.13899 141.90593]
1120 cost: 1.2220017 
Prediction:
 [149.88959 185.59064 180.01633 197.13922 141.90396]
1130 cost: 1.2195865 
Prediction:
 [149.8922  185.58891 180.01718 197.13947 141.90201]
1140 cost: 1.2171792 
Prediction:
 [149.89479 185.58717 180.01804 197.1397  141.90005]
1150 cost: 1.2147799 
Prediction:
 [149.89737 185.58542 180.01886 197.13991 141.8981 ]
1160 cost: 1.2123907 
Prediction:
 [149.89995 185.58368 180.0197  197.14012 141.89613]
1170 cost: 1.210019 
Prediction:
 [149.90253 185.58197 180.02054 197.14035 141.89421]
1180 cost: 1.2076468 
Prediction:
 [149.90512 185.58026 180.0214  197.1406  141.8923 ]
1190 cost: 1.2052952 
Prediction:
 [149.9076

### using matrix

In [22]:
x_data = [[73., 80., 75.],
          [93., 88., 93.],
          [89., 91., 90.],
          [96., 98., 100.],
          [73., 66., 70.]]
y_data = [[152.],
          [185.],
          [180.],
          [196.],
          [142.]]

In [23]:
# placeholder를 잘 잡아줘야 한다. matrix 구조가 되었기 때문에!

X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

In [25]:
W = tf.Variable(tf.random_normal([3,1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='weight')

In [26]:
# Hypothesis

hypothesis = tf.matmul(X, W) + b

# simplified cost / loss function

cost = tf.reduce_mean(tf.square(hypothesis - Y))

# Minimize

optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

In [27]:
# Launch thr graph in a session

sess = tf.Session()

# Initializes global variables in the graph
sess.run(tf.global_variables_initializer())

In [30]:
for step in range(2001):
    cost_val, hy_val, _ = sess.run(
        [cost, hypothesis, train],
        feed_dict={X : x_data, Y : y_data}
    )
    
    if step % 10 == 0:
        print(step, 'cost:', cost_val, "\nPrediction:\n", hy_val)

0 cost: 30628.215 
Prediction:
 [[-4.88957   ]
 [-1.7143157 ]
 [-4.2734127 ]
 [ 0.20729995]
 [-4.195257  ]]
10 cost: 7.755661 
Prediction:
 [[149.905  ]
 [184.3421 ]
 [179.0487 ]
 [199.83948]
 [137.721  ]]
20 cost: 7.4686785 
Prediction:
 [[150.37086]
 [184.9069 ]
 [179.6028 ]
 [200.44186]
 [138.15387]]
30 cost: 7.462011 
Prediction:
 [[150.36975]
 [184.91046]
 [179.60384]
 [200.442  ]
 [138.15865]]
40 cost: 7.4553957 
Prediction:
 [[150.36725]
 [184.91232]
 [179.60326]
 [200.44034]
 [138.16211]]
50 cost: 7.4487853 
Prediction:
 [[150.36476]
 [184.91417]
 [179.60265]
 [200.43867]
 [138.16557]]
60 cost: 7.44224 
Prediction:
 [[150.36226]
 [184.916  ]
 [179.60205]
 [200.43701]
 [138.169  ]]
70 cost: 7.4356375 
Prediction:
 [[150.35979]
 [184.91785]
 [179.60146]
 [200.43535]
 [138.17247]]
80 cost: 7.4291153 
Prediction:
 [[150.35732]
 [184.91966]
 [179.60086]
 [200.43369]
 [138.17589]]
90 cost: 7.422583 
Prediction:
 [[150.35484]
 [184.92148]
 [179.60025]
 [200.43202]
 [138.17932]]
100 co

840 cost: 6.9821715 
Prediction:
 [[150.1912 ]
 [185.04283]
 [179.56186]
 [200.31268]
 [138.41586]]
850 cost: 6.976905 
Prediction:
 [[150.1893 ]
 [185.04428]
 [179.56145]
 [200.31119]
 [138.41876]]
860 cost: 6.971595 
Prediction:
 [[150.18738]
 [185.04572]
 [179.56102]
 [200.30966]
 [138.42168]]
870 cost: 6.9663634 
Prediction:
 [[150.18549]
 [185.04715]
 [179.56061]
 [200.30817]
 [138.42456]]
880 cost: 6.961055 
Prediction:
 [[150.18361]
 [185.04858]
 [179.56018]
 [200.30664]
 [138.42746]]
890 cost: 6.95584 
Prediction:
 [[150.1817 ]
 [185.04997]
 [179.55975]
 [200.30511]
 [138.43031]]
900 cost: 6.9505897 
Prediction:
 [[150.17982]
 [185.05139]
 [179.55934]
 [200.3036 ]
 [138.4332 ]]
910 cost: 6.9453864 
Prediction:
 [[150.17796]
 [185.05281]
 [179.55891]
 [200.30211]
 [138.43607]]
920 cost: 6.94016 
Prediction:
 [[150.1761 ]
 [185.05421]
 [179.5585 ]
 [200.3006 ]
 [138.43893]]
930 cost: 6.9349847 
Prediction:
 [[150.17424]
 [185.05562]
 [179.5581 ]
 [200.2991 ]
 [138.44179]]
940 cos

1740 cost: 6.551912 
Prediction:
 [[150.04317]
 [185.15527]
 [179.53041]
 [200.1823 ]
 [138.65424]]
1750 cost: 6.547576 
Prediction:
 [[150.04178]
 [185.15636]
 [179.53014]
 [200.18092]
 [138.65666]]
1760 cost: 6.5432787 
Prediction:
 [[150.04039]
 [185.15742]
 [179.52986]
 [200.17953]
 [138.65904]]
1770 cost: 6.538968 
Prediction:
 [[150.039  ]
 [185.1585 ]
 [179.5296 ]
 [200.17816]
 [138.66145]]
1780 cost: 6.5346794 
Prediction:
 [[150.03761]
 [185.15953]
 [179.52931]
 [200.17677]
 [138.66383]]
1790 cost: 6.5303826 
Prediction:
 [[150.03624]
 [185.16058]
 [179.52904]
 [200.17538]
 [138.66621]]
1800 cost: 6.52608 
Prediction:
 [[150.03488]
 [185.16165]
 [179.52878]
 [200.17401]
 [138.66861]]
1810 cost: 6.5218515 
Prediction:
 [[150.03352]
 [185.16272]
 [179.52853]
 [200.17267]
 [138.67099]]
1820 cost: 6.5175886 
Prediction:
 [[150.03215]
 [185.16376]
 [179.52824]
 [200.17128]
 [138.67336]]
1830 cost: 6.51336 
Prediction:
 [[150.03079]
 [185.16481]
 [179.52798]
 [200.1699 ]
 [138.6757 